name: libirmin

on:
  - pull_request
  - push

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1"
          dune-cache: true
          allow-prerelease-opam: true

      - name: Install ruff and uv
        run: pip install ruff uv

      - name: Check linting
        run: ruff check

      - name: Check formatting
        run: ruff format --diff

      - name: Install opam dependencies
        run: opam install libirmin

      - run: find . -name libirmin.so

      - name: Install pip dependencies
        run: opam exec -- uv pip install --system .[dev]

      - run: opam exec -- py.test test.py
